// ==UserScript==
// @name         Zeta RM 진단 4 (플롯 조회 탐색)
// @namespace    zeta-room-manager-diag4
// @version      0.4.0
// @description  특정 플롯이 어떤 API로 조회되는지 직접 확인합니다.
// @match        https://zeta-ai.io/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==
(() => {
'use strict';if(window.top!==window.self)return;const API='https://api.zeta-ai.io',VER='3.44.7';const norm=v=>String(v||'').replace(/\s+/g,' ').trim();
function cookie(name){try{const w=name+'=';for(const p of String(document.cookie||'').split(';')){const t=p.trim();if(t.startsWith(w))return decodeURIComponent(t.slice(w.length))}}catch(_){}return''}
function tokenFrom(v){let t=norm(v);if(!t)return'';try{const p=JSON.parse(t);if(typeof p==='string')t=p;else if(p&&typeof p==='object')t=norm(p.accessToken||p.access_token||p.token||p.TOKEN)}catch(_){}t=t.replace(/^Bearer\s+/i,'');const m=t.match(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/);return m?m[0]:''}
function token(){const c=tokenFrom(cookie('TOKEN'));if(c)return c;for(const s of [localStorage,sessionStorage])try{for(let i=0;i<s.length;i++){const k=s.key(i)||'';if(!/token|auth|session/i.test(k))continue;const t=tokenFrom(s.getItem(k));if(t)return t}}catch(_){}return''}
function headers(){const t=token(),h={Accept:'application/json','X-Client-Version':VER,'X-Client-Native-Version':VER,'X-Client-Type':'web','X-Device-Type':/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)?'web':'pc_web','X-User-Language':'KOREAN'};if(t)h.Authorization='Bearer '+t;const d=norm(cookie('DEVICE_ID'));if(d)h['X-Sticky']=d;return h}
async function probe(path){try{const res=await fetch(API+path,{headers:headers(),credentials:'include',cache:'no-store'});return res.status+' — '+(await res.text()).slice(0,600)}catch(e){return'ERR '+e}}
async function findRoomRaw(plotId){let cursor='';for(let page=0;page<30;page++){const url=API+'/v2/rooms?limit=100'+(cursor?'&cursor='+encodeURIComponent(cursor):'');let json;try{const res=await fetch(url,{headers:headers(),credentials:'include',cache:'no-store'});if(!res.ok)return'방 목록 조회 실패: '+res.status;json=await res.json()}catch(e){return'방 목록 오류: '+e}for(const r of Array.isArray(json.rooms)?json.rooms:[]){const p=r.plot||{};if(norm(p.id)===plotId||norm(p.originatedId)===plotId)return JSON.stringify(r,null,1).slice(0,2500)}const next=norm(json.nextCursor);if(!next)break;cursor=next}return'(이 plotId를 가진 방을 /v2/rooms 응답에서 못 찾음)'}
async function run(plotId,body){const out=[],L=s=>{out.push(String(s));body.textContent=out.join('\n')};L('plotId: '+plotId);L('토큰: '+(token()?'있음':'없음'));L('');L('=== /v2/rooms 원본 데이터 찾는 중… ===');L(await findRoomRaw(plotId));const paths=['/v1/plots/'+plotId,'/v2/plots/'+plotId,'/v1/plots/'+plotId+'/about','/v1/plots/'+plotId+'/characters','/v1/me/plots?limit=30','/v1/plots/mine?limit=30','/v1/plots/private?limit=30','/v1/plots/created?limit=30'];L('');L('=== 엔드포인트 탐색 ===');for(const p of paths){L('');L('▶ '+p);L(await probe(p))}L('');L('완료')}
function panel(){document.getElementById('zrm-diag4')?.remove();const o=document.createElement('div');o.id='zrm-diag4';o.style.cssText='position:fixed;inset:0;z-index:2147483647;background:#111;color:#eee;font:12px/1.5 ui-monospace,monospace;padding:12px;overflow:auto;white-space:pre-wrap;word-break:break-all';const bar=document.createElement('div');bar.style.cssText='position:sticky;top:0;background:#111;padding:8px 0;display:flex;gap:8px;flex-wrap:wrap';const input=document.createElement('input');input.value='f7fcfbcb-45e6-4a96-b325-3fd366beedf7';input.style.cssText='flex:1;min-width:140px;padding:9px 12px;background:#222;color:#eee';const body=document.createElement('div');body.textContent='플롯 ID 확인하고 [실행]을 누르세요.';body.style.userSelect='text';const mk=(l,f)=>{const b=document.createElement('button');b.textContent=l;b.onclick=f;return b};bar.append(input,mk('실행',()=>run(norm(input.value),body)),mk('복사',()=>navigator.clipboard?.writeText(body.textContent)),mk('닫기',()=>o.remove()));o.append(bar,body);document.body.appendChild(o)}
function addButton(){if(!document.body||document.getElementById('zrm-diag4-btn'))return;const b=document.createElement('button');b.id='zrm-diag4-btn';b.textContent='플롯탐색';b.style.cssText='position:fixed;right:14px;bottom:278px;z-index:2147483646;padding:12px 14px';b.onclick=panel;document.body.appendChild(b)}setInterval(addButton,1000);
})();